format_version: 10
pipelines:
  test-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-f54eb87:
        git: https://github.com/sohamm-coditas/gocd-test.git
        shallow_clone: false
        auto_update: true
        branch: dev
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          print:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - sample.txt
                command: cat
                run_if: passed
